# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
   os: ubuntu-22.04
   tools:
      python: "3.9"
   apt_packages:
      # dependencies for firefox
      - bzip2
      - libxtst6
      - libgtk-3-0
      - libx11-xcb-dev
      - libdbus-glib-1-2
      - libxt6
      - libpci-dev
      - libasound2
   jobs:
      pre_install:
         - mkdir $HOME/selenium
         - mkdir $HOME/selenium/drivers
         # chrome
         - wget -N https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1047731%2Fchrome-linux.zip\?generation\=1663284576100523\&alt\=media -P $HOME
         - unzip ~/Linux_x64%2F1047731%2Fchrome-linux.zip\?generation=1663284576100523\&alt=media -d $HOME/selenium
         - rm ~/Linux_x64%2F1047731%2Fchrome-linux.zip\?generation=1663284576100523\&alt=media
         - wget -N https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_linux64.zip -P $HOME
         - unzip ~/chromedriver_linux64.zip -d $HOME/selenium/drivers
         - rm ~/chromedriver_linux64.zip
         # firefox
         - cd $HOME/selenium
         - wget -N "http://download-origin.cdn.mozilla.net/pub/firefox/releases/105.0b9/linux-x86_64/en-US/firefox-105.0b9.tar.bz2" -P $HOME/selenium
         - tar xfj $HOME/selenium/firefox-105.0b9.tar.bz2 -C $HOME/selenium
         - rm $HOME/selenium/firefox-105.0b9.tar.bz2
         - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz -P $HOME
         - tar -xvzf $HOME/geckodriver-v0.32.0-linux64.tar.gz -C $HOME/selenium/drivers
         - rm $HOME/geckodriver-v0.32.0-linux64.tar.gz

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .
   - method: pip
     path: .
     extra_requirements:
        - dev
